###############################################
### Dynamic Traefik V2 Configuration (FILE) ###
###############################################

## HTTP Middlewares
http:
  middlewares:
    ## Primitive Middlewares
    user-auth:
      basicAuth:
        usersFile: '/.htpasswd'

    gzip:
      compress: {}

    rate-limit:
      rateLimit:
        average: 100
        burst: 50

    default-secure-headers:
      headers:
        customResponseHeaders:
          X-Frame-Options: 'deny'
          Strict-Transport-Security: 'max-age=31536000 ; includeSubDomains'
          X-Content-Type-Options: 'nosniff'
          Referrer-Policy: 'no-referrer'
          sslRedirect: true

    portal-service-secure-headers:
      headers:
        customResponseHeaders:
          X-Frame-Options: 'SAMEORIGIN'
          Referrer-Policy: 'strict-origin-when-cross-origin'

    ## Chain Middlewares
    basic-auth-secured:
      chain:
        middlewares:
          - 'user-auth'
          - 'default-secure-headers'
          - 'rate-limit'
          - 'gzip'

    no-auth-secured:
      chain:
        middlewares:
          - 'default-secure-headers'
          - 'rate-limit'
          - 'gzip'

## TLS
tls:
  options:
    mintls12:
      minVersion: 'VersionTLS12' # <======= TLS 1.2 / TLS 1.3
      cipherSuites:
        - 'TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256'
        - 'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256'
        - 'TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384'
        - 'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384'
      curvePreferences:
        - 'CurveP521'
        - 'CurveP384'
      sniStrict: true
